include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  errors:
    unnecessary_getters_setters: ignore
    slash_for_doc_comments: false
    todo: ignore

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false